#ifndef PGMARK_CATEGORY_TYPES_H
#define PGMARK_CATEGORY_TYPES_H

enum class E_CATEGORY_TYPE {
    AT_BEGINNING_STRING,
    AT_BOUNDARY,
    AT_NON_BOUNDARY,
    AT_END_STRING,
    CATEGORY_DIGIT,
    CATEGORY_NOT_DIGIT,
    CATEGORY_SPACE,
    CATEGORY_NOT_SPACE,
    CATEGORY_WORD,
    CATEGORY_NOT_WORD,
    AT_BEGINNING,
    AT_END
};

#endif //PGMARK_CATEGORY_TYPES_H
